import type { Profile, Listing, Bid } from "./types";

// Stable IDs so cross-references work
export const seedProfiles: Profile[] = [
  {
    id: "u_you",
    username: "you",
    display_name: "you (demo)",
    avatar_url: "https://picsum.photos/seed/you/200",
    bio: "demo user — toggle this in the header to switch perspectives",
    reputation: 4.9,
    total_sales: 14,
    total_trades: 6,
    city: "Brooklyn, NY",
  },
  {
    id: "u_basscat",
    username: "basscat",
    display_name: "basscat",
    avatar_url: "https://picsum.photos/seed/basscat/200",
    bio: "lost lands ’22 ’23 ’24 — pashmina hoarder",
    reputation: 4.8,
    total_sales: 47,
    total_trades: 12,
    city: "Columbus, OH",
  },
  {
    id: "u_wubmom",
    username: "wubmom",
    display_name: "wubmom",
    avatar_url: "https://picsum.photos/seed/wubmom/200",
    bio: "prymal moms / excision merch / open to trades for subtronics",
    reputation: 5.0,
    total_sales: 89,
    total_trades: 31,
    city: "Denver, CO",
  },
  {
    id: "u_rifftrash",
    username: "rifftrash",
    display_name: "rifftrash",
    avatar_url: "https://picsum.photos/seed/rifftrash/200",
    bio: "no fakes. no bs.",
    reputation: 4.6,
    total_sales: 21,
    total_trades: 4,
    city: "Austin, TX",
  },
];

const now = Date.now();
const days = (n: number) => new Date(now + n * 86400000).toISOString();
const ago = (n: number) => new Date(now - n * 86400000).toISOString();

export const seedListings: Listing[] = [
  {
    id: "l_excision_hoodie_2024",
    seller_id: "u_basscat",
    title: "Excision Lost Lands ’24 Headliner Hoodie — XL",
    description:
      "Worn once at LL ’24 then washed cold inside out. Zero pilling. Heavyweight blackout fleece. Embroidered logo, screened back panel. Smoke free home.",
    brand: "Excision",
    category: "hoodie",
    size: "XL",
    condition: "like_new",
    authenticity: "official_artist",
    listing_type: "fixed_price",
    asking_price_cents: 14500,
    starting_bid_cents: null,
    buy_now_price_cents: null,
    shipping_price_cents: 1200,
    auction_ends_at: null,
    status: "active",
    images: [
      "https://picsum.photos/seed/excisionA/1200/1200",
      "https://picsum.photos/seed/excisionB/1200/1200",
      "https://picsum.photos/seed/excisionC/1200/1200",
    ],
    view_count: 421,
    open_to_trade: true,
    trade_wants: "Subtronics tee XL, Bassnectar pashmina, or cash equivalent",
    created_at: ago(2),
  },
  {
    id: "l_subtronics_tee",
    seller_id: "u_rifftrash",
    title: "Subtronics Cyclops Army Tee — L",
    description:
      "OG Cyclops Army drop tee. Tag intact. Stored flat in a closet for 8 months. Looking to fund my Lost Lands ’25 GA.",
    brand: "Subtronics",
    category: "tee",
    size: "L",
    condition: "new_with_tags",
    authenticity: "official_artist",
    listing_type: "auction",
    asking_price_cents: null,
    starting_bid_cents: 4500,
    buy_now_price_cents: 9000,
    shipping_price_cents: 800,
    auction_ends_at: days(2),
    status: "active",
    images: [
      "https://picsum.photos/seed/subtronicsA/1200/1200",
      "https://picsum.photos/seed/subtronicsB/1200/1200",
      "https://picsum.photos/seed/subtronicsC/1200/1200",
    ],
    view_count: 188,
    open_to_trade: false,
    created_at: ago(1),
  },
  {
    id: "l_basscenter_pash",
    seller_id: "u_wubmom",
    title: "Bassnectar Bass Center IX Pashmina — Holographic",
    description:
      "Holographic limited run. ~70x35in. Pristine. From a smoke free, non‑rave home (lol). Will not separate from my collection unless price/trade is right.",
    brand: "Bassnectar",
    category: "pashmina",
    size: "OS",
    condition: "like_new",
    authenticity: "festival_vendor_unofficial",
    listing_type: "trade",
    asking_price_cents: null,
    starting_bid_cents: null,
    buy_now_price_cents: null,
    shipping_price_cents: 600,
    auction_ends_at: null,
    status: "active",
    images: [
      "https://picsum.photos/seed/pashA/1200/1200",
      "https://picsum.photos/seed/pashB/1200/1200",
      "https://picsum.photos/seed/pashC/1200/1200",
    ],
    view_count: 612,
    open_to_trade: true,
    trade_wants: "ANY Subtronics pashmina, Excision Paradox poster, or 2 high‑tier Lost Lands ’23 tees",
    created_at: ago(4),
  },
  {
    id: "l_zomboy_totem",
    seller_id: "u_basscat",
    title: "Zomboy Bite The Bullet Totem — Hand‑Painted",
    description:
      "I made this for EDC ’23. Telescoping pole + LED whip‑safe collapsible top. Selling because I’m switching to a pashmina build.",
    brand: "fan_made",
    category: "totem",
    size: "OS",
    condition: "good",
    authenticity: "fan_made",
    listing_type: "fixed_price",
    asking_price_cents: 6500,
    starting_bid_cents: null,
    buy_now_price_cents: null,
    shipping_price_cents: 2400,
    auction_ends_at: null,
    status: "active",
    images: [
      "https://picsum.photos/seed/totemA/1200/1200",
      "https://picsum.photos/seed/totemB/1200/1200",
      "https://picsum.photos/seed/totemC/1200/1200",
    ],
    view_count: 73,
    open_to_trade: true,
    trade_wants: "any totem of equal craft + cash",
    created_at: ago(6),
  },
  {
    id: "l_you_riddim_cap",
    seller_id: "u_you",
    title: "Riddim Network 5‑Panel Cap — Faded Black",
    description:
      "Sun‑faded but in great shape. Adjustable strap. From the OG ’21 drop. Letting it go because I have 4 caps somehow.",
    brand: "Riddim Network",
    category: "hat",
    size: "OS",
    condition: "good",
    authenticity: "official_artist",
    listing_type: "fixed_price",
    asking_price_cents: 2500,
    starting_bid_cents: null,
    buy_now_price_cents: null,
    shipping_price_cents: 500,
    auction_ends_at: null,
    status: "active",
    images: [
      "https://picsum.photos/seed/capA/1200/1200",
      "https://picsum.photos/seed/capB/1200/1200",
      "https://picsum.photos/seed/capC/1200/1200",
    ],
    view_count: 12,
    open_to_trade: true,
    trade_wants: "any Subtronics hat, or pashminas",
    created_at: ago(0),
  },
  {
    id: "l_you_pash_oldsoul",
    seller_id: "u_you",
    title: "Bassnectar ‘Old Soul’ Pashmina — OS",
    description:
      "Soft hand. Threadbare on one corner (pictured). Selling cheap, would rather trade for Lost Lands gear.",
    brand: "Bassnectar",
    category: "pashmina",
    size: "OS",
    condition: "fair",
    authenticity: "festival_vendor_unofficial",
    listing_type: "fixed_price",
    asking_price_cents: 3200,
    starting_bid_cents: null,
    buy_now_price_cents: null,
    shipping_price_cents: 500,
    auction_ends_at: null,
    status: "active",
    images: [
      "https://picsum.photos/seed/oldsoulA/1200/1200",
      "https://picsum.photos/seed/oldsoulB/1200/1200",
      "https://picsum.photos/seed/oldsoulC/1200/1200",
    ],
    view_count: 34,
    open_to_trade: true,
    trade_wants: "Excision or Subtronics anything",
    created_at: ago(3),
  },
];

export const seedBids: Bid[] = [
  {
    id: "b1",
    listing_id: "l_subtronics_tee",
    bidder_id: "u_basscat",
    amount_cents: 5500,
    created_at: ago(0.5),
  },
  {
    id: "b2",
    listing_id: "l_subtronics_tee",
    bidder_id: "u_wubmom",
    amount_cents: 6200,
    created_at: ago(0.2),
  },
];
